### ISSUE TITLE
Issues on mobile / tablet layouts

### ISSUE THREAD

**Issue by julienbrunuk** [while42-org/while42-org.github.io#19]
Reparer des problemes mineurs lors de la consultation du site sur telephone ou tablette, voir screenshot 
![screen shot 2016-03-19 at 20 53 21 2](https://cloud.githubusercontent.com/assets/5961441/13901256/1be87d84-ee15-11e5-9182-c03d740f3914.png)

**Comment by mose** [comment]
Fixed with mr #20
