### ISSUE TITLE
update the preview image associated with the url

### ISSUE THREAD

**Issue by nbenhadj** [while42-org/while42-org.github.io#7]
when someone copies the url http://while42.org/fr/ the displayed preview is incorrect

**Comment by mose** [comment]
Tu peux nous donner un peu des elements de contexte ? Moi quand je copie une url ca contient pas de preview c'est juste une chaine de characteres. 

C'est une fonctionnalite logicielle cote OS client. Tu peux faire une capture d'ecran pour voir ?

**Comment by nbenhadj** [comment]
en copiant le l'url "http://while42.org/fr/" dans facebook (ou autre) on obtient ca:

![capturewhile42](https://cloud.githubusercontent.com/assets/11851289/7047435/cceee6fa-de0c-11e4-9f38-eaa887d5bd16.png)

c'est une évolution intéressante que l'on pourrait faire sur le site.

**Comment by mose** [comment]
D'accord donc on parle plutot des headers opengraph de facebook (qui sont aussi utilises par quelques autres sites).

On a rien effectivement a ce niveau. ca peut valoir le coup d'ajouter des headers. cf
https://developers.facebook.com/docs/sharing/webmasters#markup

**Comment by julienbrunuk** [comment]
J'ai ouvert une Pull Request: https://github.com/while42-org/while42-org.github.io/pull/9

**Comment by mose** [comment]
merci julien!
